- include: ../../common/tasks/setfacts.yml
  tags:
    - phylolink
    - deploy

- name: Install dependencies
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - python-augeas
    - python-psycopg2
    - postgresql-9.3
    - tomcat7
  tags:
    - phylolink
    - packages

- name: create DB
  postgresql_db: name=phylolink
  sudo_user: postgres
  tags:
    - phylolink
    - db

- name: create DB user
  command: "psql -d phylolink -c \"create user phylo with password '{{phylolink_db_password}}'\""
  sudo_user: postgres
  ignore_errors: yes
  tags:
    - phylolink
    - db

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/phylolink/config"
  tags:
    - deploy
    - phylolink
    - properties

- name: copy all config.properties
  template: src=phylolink-config.properties dest={{data_dir}}/phylolink/config/phylolink-config.properties
  notify:
      - restart tomcat
  tags:
    - deploy
    - phylolink
    - properties

- name: set data ownership
  file: path={{data_dir}}/phylolink owner="{{tomcat_user}}" group="{{tomcat_user}}" recurse=true
  notify:
    - restart tomcat
  tags:
    - phylolink
    - properties

- name: add nginx vhost config
  include: ../../nginx/tasks/main.yml
  vars:
    nginx_sites:
      phylojive:
        - listen 80
        - listen [::]:80
        - server_name phylojive.ala.org.au
        - return 301 http://phylolink.ala.org.au$request_uri
      phylolink:
        - listen 80
        - listen [::]:80
        - server_name {{ phylolink_hostname }}
        - client_max_body_size 500m
        - location / { proxy_set_header X-Real-IP $remote_addr; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_pass http://127.0.0.1:8080; }
    nginx_https_sites:
      phylolink:
        - listen 443 spdy
        - listen [::]:443 spdy
        - server_name {{ phylolink_hostname }}
        - ssl_certificate {{ phylolink_https_certificate_path }}
        - ssl_certificate_key {{ phylolink_https_certificate_key_path }}
        - client_max_body_size 500m
        - location / { proxy_set_header X-Real-IP $remote_addr; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_pass http://127.0.0.1:8080; }
  notify:
    - reload nginx
  tags:
    - phylolink
    - nginx_vhost
    - deploy

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ phylolink_war_url }}' context_path='{{ phylolink_context_path }}' hostname='{{ phylolink_hostname }}'
  tags:
    - phylolink
    - tomcat_vhost
    - deploy
