# application versions
collectory: collectory
# assets
version: "1.1.3"
artifactId: "collectory"
groupId: "au.org.ala"
# collectory does not need a value for classifier
classifier: ''
packaging: "war"

collectory_war_url: "{{maven_repo_ws_url}}"
