- include: ../../common/tasks/setfacts.yml

- name: download from profile-hub
  command: "wget http://nexus.ala.org.au/service/local/artifact/maven/redirect?r=releases&g=au.org.ala&a=profile-hub&v=LATEST&e=war --output-document={{tomcat_webapps}}profile-hub.war"
  tags:
    - webapps

# - name: ensure target directories exist [data subdirectories etc.]
#   file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
#   with_items:
#     - "{{data_dir}}/alerts/config"

# - name: copy all config.properties
#   template: src=alerts-config.properties dest={{data_dir}}/alerts/config/alerts-config.properties

# - name: set data ownership
#   file: path={{data_dir}}/alerts owner={{tomcat_user}} group={{tomcat_user}} recurse=true
#   notify: 
#     - restart tomcat