- include: ../../common/tasks/setfacts.yml
  tags:
    - apikey

#
# Database configuration items
#
- name: create database
  mysql_db: name={{apikey_db_name}} state=present
  register: dbschema
  tags:
    - db
    - apikey

- name: create DB user
  mysql_user: name={{apikey_db_username}} password={{ apikey_db_password}} priv=*.*:ALL state=present
  register: dbuser
  tags:
    - db
    - apikey

#
# External configuration properties file
#
- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/apikey/config"
  tags:
    - properties
    - apikey

- name: copy all config.properties
  template: src=apikey-config.properties dest={{data_dir}}/apikey/config/apikey-config.properties
  tags:
    - properties
    - apikey

- name: set data ownership
  file: path={{data_dir}}/apikey owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat
  tags:
    - properties
    - apikey

#
# WAR file deployment and virtual host configuration
#
- include: ../../apache_vhost/tasks/main.yml context_path='{{ apikey_context_path }}' hostname='{{ apikey_hostname }}'
  tags:
    - deploy
    - apache_vhost
    - apikey

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ apikey_war_url }}' context_path='{{apikey_context_path}}' hostname='{{ apikey_hostname }}'
  tags:
    - deploy
    - tomcat_vhost
    - apikey
