- include: ../../common/tasks/postgresql.yml
- include: ../../common/tasks/java.yml
- include: ../../common/tasks/tomcat.yml
- include: ../../common/tasks/apache.yml

- name: download from maven repo
  command: "wget {{images_url}} --output-document={{tomcat_webapps}}{{images_app}}.war"

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/{{images_app}}/config"

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}}  group={{tomcat_user}} 
  with_items:
    - "{{data_dir}}/images/store"
    - "{{data_dir}}/images/incoming"
    - "{{data_dir}}/images/bin/imgcnv"

- name: copy all config.properties
  template: src=config/config.properties dest={{data_dir}}/{{images_app}}/config/{{images_app}}-config.properties

- name: set data ownership
  file: path={{data_dir}}/{{images_app}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify: 
    - restart tomcat

- name: set data ownership
  file: path={{data_dir}}/images owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat