- name: Install Apache2 (RedHat)
  yum: "name=httpd state=present"
  when: ansible_os_family == "RedHat"    

- name: Start Apache2 (RedHat)
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"               

- name: Install Apache2 (Debian)
  apt: "pkg=apache2 state=present"
  when: ansible_os_family == "Debian"      

# a2enmod is debian only
- name: Enable mod proxy (Debian)
  command: a2enmod proxy_http 
  when: ansible_os_family == "Debian"         

- name: Enable mod proxy (Debian)
  command: a2enmod proxy 
  when: ansible_os_family == "Debian"               

- name: Start Apache2 (Debian)
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"    
