- include: ../../common/tasks/setfacts.yml

- name: create DB
  mysql_db: name={{specieslist_db_name}} state=present

- name: create DB user
  mysql_user: name={{specieslist_db_username}} password={{ specieslist_db_password}} priv=*.*:ALL state=present

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/specieslist-webapp/config"

- name: copy all config.properties
  template: src=specieslist-webapp-config.properties dest={{data_dir}}/specieslist-webapp/config/specieslist-webapp-config.properties

- name: set data ownership
  file: path={{data_dir}}/specieslist-webapp owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify: 
    - restart tomcat

- name: download from maven repo
  get_url: url={{ specieslist_war_url }} dest="{{tomcat_dir}}/webapps/specieslist-webapp.war" force=yes
  notify:
    - restart tomcat
 
