
########## REDHAT ########## 

- name: setup yum repo
  copy: src=yum/datastax.repo dest=/etc/yum.repos.d/datastax.repo
  when: ansible_os_family == "RedHat"   

- name: install packages (Redhat)
  yum: name={{item}} state=present
  with_items:
    - $datastax
    - $cassandra
  tags:
    - packages 
  notify: 
    - restart cassandra
    - configure cassandra
  when: ansible_os_family == "RedHat" 

- name: set cassandra to use the ByteOrderedPartitioner (RedHat)
  lineinfile: " 
    dest=/etc/cassandra/conf/cassandra.yaml  
    regexp=^partitioner 
    line='partitioner: org.apache.cassandra.dht.ByteOrderedPartitioner'"
  notify:
    - restart cassandra
  when: ansible_os_family == "RedHat"     
 

########## DEBIAN ########## 

- name: install packages (Debian)
  apt: pkg=wget  state=present
  when: ansible_os_family == "Debian" 

- name: install packages (Debian)
  apt: pkg=software-properties-common  state=present
  when: ansible_os_family == "Debian" 

- name: install packages 2 (Debian)
  apt: pkg=python-software-properties  state=present
  when: ansible_os_family == "Debian" 

- name: apt-add-repository (Debian)
  command: apt-add-repository 'deb http://debian.datastax.com/community stable main'
  when: ansible_os_family == "Debian" 

- name: get datastax repo key (Debian)
  command: wget http://debian.datastax.com/debian/repo_key --output-document=/tmp/datastax.key
  when: ansible_os_family == "Debian"   

- name: add datastax repo key  (Debian)
  command: apt-key add /tmp/datastax.key
  when: ansible_os_family == "Debian"   

- name: install Cassandra (Debian)
  apt: pkg=cassandra=1.2.10 state=present update_cache=yes
  with_items:
    - $cassandra
  tags:
    - packages 
  notify: 
    - restart cassandra
    - configure cassandra
  when: ansible_os_family == "Debian" 


- name: set cassandra to use the ByteOrderedPartitioner  (Debian)
  lineinfile: " 
    dest=/etc/cassandra/cassandra.yaml  
    regexp=^partitioner 
    line='partitioner: org.apache.cassandra.dht.ByteOrderedPartitioner'"
  notify:
    - restart cassandra
  when: ansible_os_family == "Debian"


- name: increase stack size (Debian only)
  shell: "sed -e s/Xss180k/Xss256k/g /etc/cassandra/cassandra-env.sh --in-place"
  when: ansible_os_family == "Debian"

- name: setup production settings for Cassandra (not overwrites files)
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: cassandra/90-nproc.conf, dest: /etc/security/limits.d/90-nproc.conf }
    - { src: cassandra/limits.conf, dest: /etc/security/limits.conf }
  notify: 
    - restart cassandra
