- include: ../../common/tasks/setfacts.yml
# We need to: 
#
# 1. Set in the inventory where the mounted storage is.
# 2. Test that the mounted storage exists
# 3. Create a symbolic link to the mounted storage
# 
# On CSIRO VMs the mounted storage is typically on /srv/data and we need to create a symlink from /data -> /srv/data 
# On Nectar & EC2 Ubuntu VMs this is usually /mnt  
#
# - name: ensure local repository exists [happens locally]
#   action: file dest={{local_repo_dir}} state=directory force=yes


- file: path={{ data_dir }} state=directory mode=0755
  when: is_vagrant is defined and is_vagrant == True

- stat: path={{ data_dir }}
  register: data_dir_stat

- debug: msg="data directory {{ data_dir }} exists already"
  when: data_dir_stat.stat.isdir is defined and data_dir_stat.stat.exists == True

- debug: msg="data directory {{ data_dir }} is NOT defined (path does not exist)"
  when: data_dir_stat.stat.isdir is not defined 

- name: apt-get update (Debian)
  command: "apt-get update"
  when: ansible_os_family == "Debian"
  tags:
    - apt_update  