- name: debconf (Debian)
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: ansible_os_family == "Debian"   

- name: debconf2 (Debian)
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  when: ansible_os_family == "Debian"   

- name: install software-properties-common (Debian)
  apt: pkg=software-properties-common  state=present update_cache=yes
  when: ansible_os_family == "Debian" 

- name: install python-software-properties (Debian)
  apt: pkg=python-software-properties  state=present update_cache=yes
  when: ansible_os_family == "Debian" 

- name: apt-add-repository (Debian)
  command: apt-add-repository -y ppa:webupd8team/java
  when: ansible_os_family == "Debian" 

- name: install oracle 7 java (Debian) - 50% of the time this works everytime
  apt: pkg=oracle-java7-installer state=present update_cache=yes
  when: ansible_os_family == "Debian"   

- name: set oracle 7 java  (Debian)
  apt: pkg=oracle-java7-set-default
  when: ansible_os_family == "Debian"   


#sudo add-apt-repository ppa:webupd8team/java
#sudo apt-get update
#sudo apt-get install oracle-java7-installer
#It'll keep your java 7 installation up to date.

#To automatically set up the Java 7 environment variables JAVA_HOME and PATH:

#sudo apt-get install oracle-java7-set-default

#- name: Install wget
#  apt: pkg=wget

#- name: Download Java
#  command: "wget --no-check-certificate --no-cookies --output-document={{java_archive}} --header \"Cookie: oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz"

#- name: Extract Java archive
#  command: "tar -xzf {{java_archive}} -C {{download_folder}} creates={{download_folder}}/{{java_name}}"

#- name: Fix ownership 
#  file: "state=directory path={{download_folder}}/{{java_name}} owner=root group=root recurse=yes"

#- name: Create Java folder
#  file: "state=directory path={{java_folder}}"

##- name: Move Java to final folder
 # command: "mv {{download_folder}}/{{java_name}} {{java_folder}} creates={{java_folder}}/{{java_name}}"

#- name: Create symlink for easier update
#  file: "state=link src={{java_folder}}/{{java_name}} dest={{java_folder}}/{{java_alias}}"

#- name: Make Java available for system
#  command: "update-alternatives --install \"/usr/bin/java\" \"java\" \"{{java_folder}}/{{java_alias}}/bin/java\" 1"

#- name: Make Java available for system
#  command: "update-alternatives --set java {{java_folder}}/{{java_alias}}/bin/java"