# set up tomcat consistently whenever needed.  Used as:
# - include: ../common/tasks/tomcat.yml 
# "tomcat" variable controls version (@see common/vars)
- include: setfacts.yml 

- name: install tomcat (RedHat)
  yum: name={{tomcat}} state=present
  tags:
    - packages 
  notify: 
    - restart tomcat
  when: ansible_os_family == "RedHat"     

- name: install tomcat (Debian)
  apt: pkg={{tomcat}} state=present update_cache=yes
  tags:
    - packages 
  notify: 
    - restart tomcat
  when: ansible_os_family == "Debian"     

# replace the commented out java_opts that ships with the CentOS install which is:
# JAVA_OPTS="-Xminf0.1 -Xmaxf0.3"        
- name: configure tomcat memory (RedHat)
  lineinfile: 
    dest={{tomcat_conf}}
    regexp="-Djava.awt.headless=true -Xmx128m"
    line='JAVA_OPTS="{{tomcat_java_opts}}"'
  notify: 
    - restart tomcat
  when: ansible_os_family == "RedHat" 


- name: configure tomcat memory (Debian)
  lineinfile: 
    dest={{tomcat_conf}}
    regexp="-Xminf0.1 -Xmaxf0.3"
    line='JAVA_OPTS="{{tomcat_java_opts}}"'
  notify: 
    - restart tomcat
  when: ansible_os_family == "Debian" 


- name: Set JAVA_HOME  (Debian)
  lineinfile: " 
    dest={{tomcat_conf}}
    regexp=^JAVA_HOME
    line='JAVA_HOME=/usr/lib/jvm/java-7-oracle'"
  notify: 
    - restart tomcat    
  when: ansible_os_family == "Debian"