- include: ../../common/tasks/setfacts.yml

- name: Copy proxy config to conf.d (Redhat)
  copy: src=centos-proxies.conf dest=/etc/httpd/conf.d/
  when: ansible_os_family == "RedHat" 

- name: Copy proxy config to sites-available (Debian)
  copy: src=demo.conf dest=/etc/apache2/sites-available/ owner=root group=root
  when: ansible_os_family == "Debian" 

- name: Copy proxy config to sites-available (Debian)
  command: "rm /etc/apache2/sites-enabled/*" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 

- name: Create symlink to sites-enabled (Debian)
  command: "rm /etc/apache2/sites-enabled/000-default" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 

- name: Create symlink to sites-enabled (Debian)
  command: "ln -sf /etc/apache2/sites-available/demo.conf /etc/apache2/sites-enabled/demo" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 

- name: Copy welcome page (RedHat)
  template: src=index.html dest=/var/www/html/index.html mode=0666
  when: ansible_os_family == "RedHat"     
  tags:
    - demo_apache

- name: Copy welcome page (Debian)
  template: src=index.html dest=/var/www/index.html mode=0666
  when: ansible_os_family == "Debian"       
  tags:
    - demo_apache

- name: Start Apache2
  service: name={{apache}} state=restarted
