- include: ../../common/tasks/setfacts.yml

- name: ensure lucene directory exists 
  file: path={{data_dir}}/lucene state=directory owner={{tomcat_user}} group={{tomcat_user}}
  tags:
    - "nameindex"  

- name: Download lucene index
  get_url: url={{lucene_namematching_url}} dest={{data_dir}}/lucene/col_namematching.tgz
  tags:
    - "nameindex"  

- name: unpackage the lucene index if it was newly copied
  shell: "tar xvf {{data_dir}}/lucene/col_namematching.tgz -C {{data_dir}}/lucene/"
  tags:
    - "nameindex"  

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/lucene owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  tags:
    - "nameindex"