- include: ../../common/tasks/setfacts.yml

- name: Copy proxy config to conf.d (Redhat)
  template: src=centos-proxies.conf dest=/etc/httpd/conf.d/
  when: ansible_os_family == "RedHat" 

- name: Copy proxy config to sites-available (Debian)
  template: src=hub.conf dest=/etc/apache2/sites-available/ owner=root group=root
  when: ansible_os_family == "Debian" 

- name: Create symlink to sites-enabled (Debian)
  command: "find /etc/apache2/sites-enabled/ -type l -delete" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 

- name: Create symlink to sites-enabled (Debian)
  command: "ln -fs /etc/apache2/sites-available/hub.conf /etc/apache2/sites-enabled/hub" 
  ignore_errors: yes
  when: ansible_os_family == "Debian" 

- name: Start Apache2
  service: name={{apache}} state=restarted
