# dependency versions
datastax: dsc12-1.2.10-1
cassandra: cassandra12-1.2.10-1

# war location in maven repo
version: "1.3"
biocache_service_war_path: "{{maven_repo}}/service/local/artifact/maven/redirect?r=public&g=au.org.ala&a=biocache-service&v={{version}}&e=war"

local_repo_dir: ~/.ala