# dependency versions
datastax: dsc12-1.2.10-1
cassandra: cassandra12-1.2.10-1

# war location in maven repo
#biocache_service_war_path: http://nexus.ala.org.au/service/local/artifact/maven/redirect?r=snapshots&g=au.org.ala&a=biocache-service&v=LATEST&e=war
biocache_service_war_path: http://nexus.ala.org.au/service/local/artifact/maven/redirect?r=releases&g=au.org.ala&a=biocache-service&v=1.3&e=war

local_repo_dir: ~/.ala