- include: ../../common/tasks/setfacts.yml

- name: copy transient files to tmp (schemas etc)
  copy: src={{item}} dest=/tmp
  with_items:
    - collectory-sequences.sql
  tags:
    - createdb

- name: ensure mysql is running (this is idempotent so safe)
  service: name={{mysql_service}} state=started
  tags:
    - mysql

- name: create collectory DB
  mysql_db: name=collectory state=present

- name: create collectory DB user
  mysql_user: name={{collectory_db_user}} password={{collectory_db_password}} priv=collectory.*:ALL state=present

- name: create collectory sequences
  shell: "{{item}}"
  with_items:
    - "mysql -u root -e 'CREATE DATABASE IF NOT EXISTS collectory'"
    - "mysql -u root collectory < /tmp/collectory-sequences.sql"
  tags:
    - createdb