- include: ../../common/tasks/setfacts.yml 

- name: download wkhtmltopdf deb
  get_url: 'url=http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-precise-i386.deb dest=/tmp/wkhtmltopdf.deb'

- name: install wkhtmltopdf deb
  apt: deb=/tmp/wkhtmltopdf.deb
