- include: ../../common/tasks/setfacts.yml
  tags:
    - webapps
    - config
    - bie-index

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{ data_dir }}/bie-index/config"    
    - "{{ data_dir }}/bie/import"     
  tags:
    - config
    - bie-index

- name: copy all config.properties
  template: src=bie-index-config.properties dest={{data_dir}}/bie-index/config/bie-index-config.properties force=yes
  tags:
    - webapps
    - config
    - bie-index

- include: ../../apache_vhost/tasks/main.yml context_path='/{{ bie_index_context_path }}' hostname='{{ bie_index_hostname }}'
  tags:
    - webapps
    - apache_vhost
    - deploy
    - bie-index 

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ bie_index_war_url }}' context_path='{{ bie_index_context_path }}' hostname='{{ bie_index_hostname }}'
  tags:
    - webapps
    - tomcat_vhost
    - deploy
    - bie-index

- name: copy all data assets
  copy: src=subgroups.json dest=/srv/{{bie_index_hostname}}/www/
  tags:
    - bie-index