- name: create database
  postgresql_db: name={{db_name}}
  sudo_user: postgres
  sudo: True
  tags:
    - postgresql_instance

- name: create database user
  postgresql_user: db={{db_name}} name={{db_username}} password={{db_password}} priv=ALL state=present
  sudo_user: postgres
  sudo: True
  tags:
    - postgresql_instance
