- include: ../../common/tasks/setfacts.yml
  tags:
    - webapi

- name: ensure target directories exist [data subdirectories etc.]
  file: path="{{ data_dir }}/webapi/config" state=directory owner={{tomcat_user}} group={{tomcat_user}}
  notify:
    - restart tomcat
  tags:
    - webapi
    - config

- name: copy all config.properties
  template: src=webapi-config.properties.j2 dest={{data_dir}}/webapi/config/webapi-config.properties
  notify:
    - restart tomcat
  tags:
    - webapi
    - config

- name: set data ownership
  file: path={{data_dir}}/webapi owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat
  tags:
    - webapi
    - config

- name: ensure tomcat vhost webapps directory exists
  file: path="{{tomcat_dir}}/webapps-webapi" state=directory owner={{tomcat_user}} group={{tomcat_user}}
  notify:
    - restart tomcat
  tags:
    - webapi
    - config

- name: symlink /usr/share/tomcat6 to new webapps directory
  file: dest=/usr/share/tomcat6/webapps-webapi src="{{tomcat_dir}}/webapps-webapi" state=link
  when: ansible_os_family == "RedHat"
  notify:
    - restart tomcat
  tags:
    - webapi
    - tomcat

- name: download from maven repo
  get_url: url={{ webapi_url }} dest="{{tomcat_dir}}/webapps-webapi/ROOT.war"
  notify:
    - restart tomcat
  tags:
    - webapi
    - tomcat

- name: create tomcat vhost
  tomcat_vhost: name=webapi aliases={{ hostname }}
  notify:
    - restart tomcat
  tags:
    - webapi
    - tomcat

- name: Copy proxy config to conf.d (Redhat)
  template: src=webapi.j2 dest=/etc/httpd/conf.d/webapi-vhost.conf
  when: ansible_os_family == "RedHat" 
  notify: 
    - restart apache
  tags:
    - webapi
    - apache

- name: Create Volunteer Portal virtual host config file (Debian)
  template: src=webapi.j2 dest=/etc/apache2/sites-available/webapi.conf owner=root group=root
  when: ansible_os_family == "Debian" 
  notify:
    - reload apache
  tags:
    - webapi
    - apache

- name: Enable webapi virtual host (Debian)
  command: "a2ensite webapi"
  when: ansible_os_family == "Debian" 
  notify:
    - reload apache
  tags:
    - webapi
    - apache
