- include: ../../common/tasks/setfacts.yml
  tags:
    - calendars
    - deploy
#
# External configuration properties file
#
- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/calendars/config"
  tags:
    - properties
    - calendars

- name: copy all config.properties
  template: src=calendars-config.properties dest={{data_dir}}/calendars/config/calendars-config.properties
  tags:
    - properties
    - calendars

- name: set data ownership
  file: path={{data_dir}}/calendars owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat
  tags:
    - properties
    - calendars


#
# WAR file deployment and virtual host configuration
#
- include: ../../apache_vhost/tasks/main.yml context_path='{{ calendars_context_path }}' hostname='{{ calendars_hostname }}'
  tags:
    - deploy
    - apache_vhost
    - calendars

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ calendars_war_url }}' context_path='{{calendars_context_path}}' hostname='{{ calendars_hostname }}'
  tags:
    - deploy
    - tomcat_vhost
    - calendars

#
# Override the default memory settings for Tomcat to increase heap space and change the garbage collector
#
- name: Override default tomcat memory configuration
  lineinfile:
    dest={{tomcat_conf}}
    regexp="^JAVA_OPTS"
    line='JAVA_OPTS="{{tomcat_java_opts_override}}"'
  notify:
    - restart tomcat
  tags:
    - calendars
    - deploy
    - tomcat

#
# Cron Job configuration
#
- name: install cron job for indexing elastic search
  cron: minute=21 hour=22 name="Elastic search indexing" job="wget -O - {{ calendars_url }}{{ calendars_context_path }}/admin/reIndexAll >/dev/null 2>&1" user=root state=present

#
# Copy sensitive data xml file
#  
- name: Copy config files to config directory
  copy: src=sensitive-species-data.xml dest={{data_dir}}/calendars/config/sensitive-species-data.xml
  tags:
    - calendars
    - properties  
