fieldguide_app: fieldguide
#fieldguide_url: "{{maven_repo}}/au/org/ala/ala-fieldguide/1.0-SNAPSHOT/ala-fieldguide-1.0-SNAPSHOT.war"
fieldguide_url: http://nexus.ala.org.au/service/local/artifact/maven/redirect?r=releases&g=au.org.ala&a=fieldguide&v=LATEST&e=war