- hosts: ala-hub-standalone
  roles:
    - common
    - java
    - tomcat
    - apache
    - { role: biocache-hub, biocache_hub: ala-hub }
    - { role: hub-ala-tomcat, biocache_hub: ala-hub }
    - { role: hub-apache }