- hosts: appd
  roles:
#   - common
#   - java
#   - tomcat
    - cassandra
#   - mysql
    - apache
    - nameindex
    - solr
    - biocache-db
    - biocache-service
    - { role: biocache-hub, biocache_hub: appd-hub }
    - cli
