- hosts: appd
  roles:
    - common
    - java
    - tomcat
    - cassandra
    - apache
    - nameindex
    - solr
    - biocache-db
    - biocache-service
    - { role: biocache-hub, biocache_hub: appd-hub }
    - biocache-cli
