- hosts: layers-service
  roles:
    - java
    - common
    - tomcat
    - apache
    - geoserver
    - postgresql    
    - { role: postgresql_instance, db_name: "{{ layers_db_name | default('layersdb')}}",  db_username: "{{ layers_db_username | default('postgres') }}", db_password: "{{ layers_db_password | default('password') }}" }
    - layers-service
    - layer-ingestion