- hosts: mdba-hub-standalone
  roles:
    - common
    - java
    - tomcat
    - apache
    - { role: biocache-hub, biocache_hub: mdba-hub }
 # - { role: biocache-hub, biocache_hub: avh-hub, proxy_root_context_to: avh-hub }
