- hosts: mdba-hub-standalone
  roles:
    - common
    - java
    - tomcat
    - apache
    - { role: biocache-hub, biocache_hub: mdba-hub, grouped_facets_json: grouped_facets_mdba.json  }
 # - { role: biocache-hub, biocache_hub: avh-hub, proxy_root_context_to: avh-hub }
