- hosts: phylolink
  roles:
    - phylolink-dependencies
    - web2py
    - web2PyApps
    - common
    - nameindex
    - java
    - tomcat
    - nginx
    - phylolink
  become: yes
  become_user: root
  vars:
    deleteWeb2py: False
    deletePhylesystem: False
    deleteNCL: False
    deleteToNexml: False
