- include: ../../common/tasks/setfacts.yml

- name: add common tomcat jars (for SOLR logging and JTS)
  copy: src=tomcat/libs/{{item}} dest=/usr/share/{{tomcat}}/lib/{{item}}
  with_items:
    - jcl-over-slf4j-1.6.6.jar
    - jts-1.12.jar
    - jul-to-slf4j-1.6.6.jar
    - log4j-1.2.16.jar
    - slf4j-api-1.6.6.jar
    - slf4j-log4j12-1.6.6.jar
  notify:
    - restart tomcat

- name: copy SOLR webapps
  copy: src=tomcat/webapps/{{solr}}.war dest=/var/lib/{{tomcat}}/webapps/solr.war

- name: ensure tomcat context directory exists
  file: path=/usr/share/{{tomcat}}/conf/Catalina/localhost/ state=directory owner={{tomcat_user}} group={{tomcat_user}}
  notify:
    - restart tomcat

- name: copy SOLR context (Redhat)
  template: src=context/solr.xml dest=/usr/share/{{tomcat}}/conf/Catalina/localhost/solr.xml owner={{tomcat_user}}  group={{tomcat_user}}
  notify:
    - restart tomcat
  when: ansible_os_family == "RedHat"

- name: copy SOLR context  (Debian)
  template: src=context/solr.xml dest=/var/lib/{{tomcat}}/conf/Catalina/localhost/solr.xml owner={{tomcat_user}}  group={{tomcat_user}}
  notify:
    - restart tomcat
  when: ansible_os_family == "Debian"

- name: ensure target directories exist [data subdirectories etc.
  file: path={{item}} state=directory owner={{tomcat_user}}  group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/solr/biocache/conf"

- name: copy SOLR config
  copy: src=solr dest={{data_dir}} owner={{tomcat_user}}  group={{tomcat_user}}

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/{{item}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  with_items:
    - solr

- name: set SOLR directory ownership [all data is owned by tomcat]
  file: path={{data_dir}}/solr owner={{tomcat_user}} group={{tomcat_user}}  recurse=true
