tomcat_webapps: /var/lib/tomcat7/webapps/
volunteer_context_path: /

local_repo_dir: ~/.ala
data_dir: /srv/data
version: "1.0"
volunteers_url: "{{maven_repo}}/service/local/artifact/maven/redirect?r=public&g=au.org.ala&a=volunteer-portal&v={{version}}&e=war"
volunteer_app: volunteer-portal
tomcat_ajp: true
tomcat_http: false
tomcat_autoDeploy: true
tomcat_bind_addr: '127.0.0.1' 