- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present
  when: ansible_os_family == "Debian" 
  tags: postgresql

- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  when: ansible_os_family == "Debian" 
  tags: postgresql

- name: Install PostGIS
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - build-essential 
    - libgeos-c1 
    - libproj-dev 
    - libjson-c-dev 
    - libxml2-dev 
    - libxml2-utils 
    - xsltproc 
    - docbook-xsl 
    - docbook-mathml 
    - libpq-dev
    - libxml2 
    - libc6
    - libproj0 
    - imagemagick 
    - dblatex
    - postgresql-9.2
    - postgresql-server-dev-9.2

###### TO ADD

# wget http://download.osgeo.org/geos/geos-3.3.8.tar.bz2
# tar xvfj geos-3.3.8.tar.bz2
# cd geos-3.3.8
# ./configure
# make
# sudo make install
# cd

# wget http://download.osgeo.org/postgis/source/postgis-1.5.8.tar.gz
# tar xfvz postgis-1.5.8.tar.gz
# cd postgis-1.5.8
# ./configure
# make
# sudo make install
# sudo ldconfig
# cd

# psql -d layersdb -f /usr/share/postgresql/9.2/contrib/postgis-1.5/postgis.sql
# psql -d layersdb -f /usr/share/postgresql/9.2/contrib/postgis-1.5/spatial_ref_sys.sql
